DROP DATABASE IF EXISTS ecommerce_db;
CREATE DATABASE ecommerce_db;

USE ecommerce_db;

CREATE TABLE category (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    catName VARCHAR(100) NOT NULL
);

CREATE TABLE product (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    productName VARCHAR(100) NOT NULL,
    price DECIMAL NOT NULL,
    stock INT NOT NULL DEFAULT 10 CHECK (stock >= 0),
	category INT, 
	FOREIGN KEY (category) REFERENCES category (id)
	ON DELETE SET NULL
);

CREATE TABLE tag (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tagName VARCHAR(100) NOT NULL
);

CREATE TABLE productTag (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product INT,
    tag INT,
	FOREIGN KEY (product) REFERENCES product (id),
	FOREIGN KEY (tag) REFERENCES tag (id)
	ON DELETE SET NULL
);

